//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TwinCAT_Commander.rc
//
#define IDD_TWINCAT_COMMANDER_DIALOG					102
#define IDR_MAINFRAME									128
#define IDC_BTN_DISCONNECT								1003
#define IDC_LIST_MSG									1004
#define IDC_COMBO_ELMO_SEL								1005
#define IDC_BTN_CONNECT									1006
#define IDC_BTN_PRINT_SYMBOL							1007
#define IDC_BTN_MSG_CLEAR								1008
#define IDC_STATIC_ELMO_STATE							1009
#define IDC_STATIC_ELMO_SERVO_MODE						1010
#define IDC_STATIC_ELMO_SERVO_STATUS					1011
#define IDC_STATIC_ELMO_TARGET_REACH					1012
#define IDC_STATIC_ELMO_POS								1013
#define IDC_STATIC_ELMO_VELO							1014
#define IDC_STATIC_ELMO_TORQ							1015
#define IDC_BTN_PRINT_ELMO_INFO							1016
#define IDC_STATIC_ELMO_CURR							1017
#define IDC_STATIC_ADS_STATE							1021
#define IDC_BTN_HapticD_LEFT_POS_MODE					1023
#define IDC_BTN_HapticD_LEFT_VEL_MODE					1024
#define IDC_BTN_HapticD_LEFT_TORQ_MODE					1025
#define IDC_BTN_HapticD_LEFT_HOMING_MODE				1026
#define IDC_BTN_HapticD_LEFT_SERVO_ON					1027
#define IDC_BTN_HapticD_LEFT_SERVO_OFF					1028
#define IDC_BTN_HapticD_LEFT_SERVO_QUICK_STOP			1029
#define IDC_BTN_HapticD_LEFT_HOME_SEARCH				1030
#define IDC_BTN_HapticD_LEFT_INIT_FT_SENSOR				1031
#define IDC_RADIO_SELE_ELMO1							1032
#define IDC_RADIO_SELE_ELMO2							1033
#define IDC_BTN_HapticD_RIGHT_VEL_MODE							1034
#define IDC_BTN_HapticD_RIGHT_HOMING_MODE						1035
#define IDC_BTN_HapticD_RIGHT_POS_MODE							1036
#define IDC_BTN_HapticD_RIGHT_TORQ_MODE							1037
#define IDC_BTN_HapticD_RIGHT_SERVO_ON							1038
#define IDC_BTN_HapticD_RIGHT_SERVO_OFF							1039
#define IDC_BTN_HapticD_RIGHT_SERVO_QUICK_STOP					1040
#define IDC_BTN_POS_MODE_HOME							1041
#define IDC_BTN_POS_MODE_JOB							1042
#define IDC_BTN_POS_MODE_POSE1							1043
#define IDC_BTN_POS_MODE_POSE2							1044
#define IDC_BTN_HOME_SEARCH_RIGHT						1045
#define IDC_BTN_HapticD_RIGHT_INIT_FT_SENSOR					1046
#define IDC_STATIC_HapticD_RIGHT_CALI_HAND				1421
#define IDC_BTN_HapticD_RIGHT_CALI_HAND					1422
#define IDC_BTN_POS_MODE_POSE3							1047
#define IDC_STATIC_HapticD_LEFT_HOME_SEARCH				1103
#define IDC_STATIC_HapticD_LEFT_CALI_HAND				1419
#define IDC_BTN_HapticD_LEFT_CALI_HAND					1420
#define IDC_STATIC_HapticD_LEFT_INIT_FT					1104
#define IDC_STATIC_HOME_SEARCH_RIGHT					1105
#define IDC_STATIC_HapticD_RIGHT_INIT_FT						1106
#define IDC_BTN_HapticD_LEFT_HOME_SEARCH_BREAK			1108
#define IDC_EDIT_POS_MODE_TIME							1109
#define IDC_BTN_HOME_SEARCH_BREAK_RIGHT					1110
#define IDC_STATIC_TASK_CYCLE_TIME      1111
#define IDC_STATIC_ALGORITHM_TIME       1112
#define IDC_EDIT_HapticD_LEFT_POS1             1113
#define IDC_EDIT_HapticD_LEFT_POS2             1114
#define IDC_EDIT_HapticD_LEFT_POS3             1115
#define IDC_EDIT_HapticD_LEFT_POS4             1116
#define IDC_EDIT_HapticD_LEFT_POS5             1117
#define IDC_EDIT_HapticD_LEFT_POS6             1118
#define IDC_EDIT_VIRTUAL_LEFT_POS1                 1119
#define IDC_EDIT_VIRTUAL_LEFT_POS2                 1120
#define IDC_EDIT_VIRTUAL_LEFT_POS3                 1121
#define IDC_EDIT_VIRTUAL_LEFT_POS4                 1122
#define IDC_EDIT_VIRTUAL_LEFT_POS5                 1123
#define IDC_EDIT_VIRTUAL_LEFT_POS6                 1124
#define IDC_EDIT_HapticD_LEFT_FINGER1_POS1             1125
#define IDC_EDIT_HapticD_LEFT_FINGER1_POS2             1126
#define IDC_EDIT_HapticD_LEFT_FINGER1_POS3             1127
#define IDC_EDIT_HapticD_LEFT_FINGER1_POS4             1128
#define IDC_EDIT_HapticD_LEFT_FINGER1_POS5             1129
#define IDC_EDIT_HapticD_LEFT_FINGER1_POS6             1130
#define IDC_EDIT_HapticD_LEFT_FINGER2_POS1             1131
#define IDC_EDIT_HapticD_LEFT_FINGER2_POS2             1132
#define IDC_EDIT_HapticD_LEFT_FINGER2_POS3             1133
#define IDC_EDIT_HapticD_LEFT_FINGER2_POS4             1134
#define IDC_EDIT_HapticD_LEFT_FINGER2_POS5             1135
#define IDC_EDIT_HapticD_LEFT_FINGER2_POS6             1136
#define IDC_EDIT_HapticD_LEFT_FINGER3_POS1             1137
#define IDC_EDIT_HapticD_LEFT_FINGER3_POS2             1138
#define IDC_EDIT_HapticD_LEFT_FINGER3_POS3             1139
#define IDC_EDIT_HapticD_LEFT_FINGER3_POS4             1140
#define IDC_EDIT_HapticD_LEFT_FINGER3_POS5             1141
#define IDC_EDIT_HapticD_LEFT_FINGER3_POS6             1142
#define IDC_EDIT_HapticD_LEFT_FT1                  1143
#define IDC_EDIT_HapticD_LEFT_FT2                  1144
#define IDC_EDIT_HapticD_LEFT_FT3                  1145
#define IDC_EDIT_HapticD_LEFT_FT4                  1146
#define IDC_EDIT_HapticD_LEFT_FT5                  1147
#define IDC_EDIT_HapticD_LEFT_FT6                  1148
#define IDC_EDIT_VIRTUAL_LEFT_FT1                 1149
#define IDC_EDIT_VIRTUAL_LEFT_FT2                 1150
#define IDC_EDIT_VIRTUAL_LEFT_FT3                 1151
#define IDC_EDIT_VIRTUAL_LEFT_FT4                 1152
#define IDC_EDIT_VIRTUAL_LEFT_FT5                 1153
#define IDC_EDIT_VIRTUAL_LEFT_FT6                 1154
#define IDC_EDIT_VIRTUAL_LEFT_FINGER1_POS1             1155
#define IDC_EDIT_VIRTUAL_LEFT_FINGER1_POS2             1156
#define IDC_EDIT_VIRTUAL_LEFT_FINGER1_POS3             1157
#define IDC_EDIT_VIRTUAL_LEFT_FINGER1_POS4             1158
#define IDC_EDIT_VIRTUAL_LEFT_FINGER1_POS5             1159
#define IDC_EDIT_VIRTUAL_LEFT_FINGER1_POS6             1160
#define IDC_EDIT_VIRTUAL_LEFT_FINGER2_POS1             1161
#define IDC_EDIT_VIRTUAL_LEFT_FINGER2_POS2             1162
#define IDC_EDIT_VIRTUAL_LEFT_FINGER2_POS3             1163
#define IDC_EDIT_VIRTUAL_LEFT_FINGER2_POS4             1164
#define IDC_EDIT_VIRTUAL_LEFT_FINGER2_POS5             1165
#define IDC_EDIT_VIRTUAL_LEFT_FINGER2_POS6             1166
#define IDC_EDIT_VIRTUAL_LEFT_FINGER3_POS1             1167
#define IDC_EDIT_VIRTUAL_LEFT_FINGER3_POS2             1168
#define IDC_EDIT_VIRTUAL_LEFT_FINGER3_POS3             1169
#define IDC_EDIT_VIRTUAL_LEFT_FINGER3_POS4             1170
#define IDC_EDIT_VIRTUAL_LEFT_FINGER3_POS5             1171
#define IDC_EDIT_VIRTUAL_LEFT_FINGER3_POS6             1172
#define IDC_CHECK_HapticD_LEFT_FRIC                  1175
#define IDC_CHECK_HapticD_LEFT_GRAV                  1176
#define IDC_CHECK_HapticD_LEFT_CTRL                  1177
#define IDC_EDIT_HapticD_LEFT_FRIC1                 1182
#define IDC_EDIT_HapticD_LEFT_FRIC2                 1183
#define IDC_EDIT_HapticD_LEFT_FRIC3                 1184
#define IDC_EDIT_HapticD_LEFT_FRIC4                 1185
#define IDC_EDIT_HapticD_LEFT_FRIC5                 1186
#define IDC_EDIT_HapticD_LEFT_FRIC6                 1187
#define IDC_EDIT_HapticD_LEFT_GRAV1                 1188
#define IDC_EDIT_HapticD_LEFT_GRAV2                 1189
#define IDC_EDIT_HapticD_LEFT_GRAV3                 1190
#define IDC_EDIT_HapticD_LEFT_GRAV4                 1191
#define IDC_EDIT_HapticD_LEFT_GRAV5                 1192
#define IDC_EDIT_HapticD_LEFT_GRAV6                 1193
#define IDC_EDIT_HapticD_LEFT_CTRL1                 1194
#define IDC_EDIT_HapticD_LEFT_CTRL2                 1195
#define IDC_EDIT_HapticD_LEFT_CTRL3                 1196
#define IDC_EDIT_HapticD_LEFT_CTRL4                 1197
#define IDC_EDIT_HapticD_LEFT_CTRL5                 1198
#define IDC_EDIT_HapticD_LEFT_CTRL6                 1199
#define IDC_EDIT_HapticD_LEFT_Tq1                   1201
#define IDC_EDIT_HapticD_LEFT_Tq2                   1202
#define IDC_EDIT_HapticD_LEFT_Tq3                   1203
#define IDC_EDIT_HapticD_LEFT_Tq4                   1204
#define IDC_EDIT_HapticD_LEFT_Tq5                   1205
#define IDC_EDIT_HapticD_LEFT_Tq6                   1206
#define IDC_EDIT_HapticD_LEFT_GAIN1         1207
#define IDC_EDIT_HapticD_LEFT_GAIN2         1208
#define IDC_EDIT_HapticD_LEFT_GAIN3         1209
#define IDC_EDIT_HapticD_LEFT_GAIN4         1210
#define IDC_EDIT_HapticD_LEFT_GAIN5         1211
#define IDC_EDIT_HapticD_LEFT_GAIN6         1212
#define IDC_EDIT_HapticD_LEFT_GAIN7         1213
#define IDC_EDIT_HapticD_LEFT_GAIN8         1214
#define IDC_BUTTON_HapticD_LEFT_GAIN                 1215



#define IDC_EDIT_HapticD_RIGHT_POS1             1313
#define IDC_EDIT_HapticD_RIGHT_POS2             1314
#define IDC_EDIT_HapticD_RIGHT_POS3             1315
#define IDC_EDIT_HapticD_RIGHT_POS4            1316
#define IDC_EDIT_HapticD_RIGHT_POS5            1317
#define IDC_EDIT_HapticD_RIGHT_POS6            1318
#define IDC_EDIT_HapticD_RIGHT_FT1                  1319
#define IDC_EDIT_HapticD_RIGHT_FT2                  1320
#define IDC_EDIT_HapticD_RIGHT_FT3                  1321
#define IDC_EDIT_HapticD_RIGHT_FT4                 1322
#define IDC_EDIT_HapticD_RIGHT_FT5                 1323
#define IDC_EDIT_HapticD_RIGHT_FT6                 1324
#define IDC_EDIT_HapticD_RIGHT_FINGER1_POS1             1325
#define IDC_EDIT_HapticD_RIGHT_FINGER1_POS2             1326
#define IDC_EDIT_HapticD_RIGHT_FINGER1_POS3             1327
#define IDC_EDIT_HapticD_RIGHT_FINGER1_POS4            1328
#define IDC_EDIT_HapticD_RIGHT_FINGER1_POS5            1329
#define IDC_EDIT_HapticD_RIGHT_FINGER1_POS6            1330
#define IDC_EDIT_HapticD_RIGHT_FINGER2_POS1				1331
#define IDC_EDIT_HapticD_RIGHT_FINGER2_POS2				1332
#define IDC_EDIT_HapticD_RIGHT_FINGER2_POS3				1333
#define IDC_EDIT_HapticD_RIGHT_FINGER2_POS4				1334
#define IDC_EDIT_HapticD_RIGHT_FINGER2_POS5				1335
#define IDC_EDIT_HapticD_RIGHT_FINGER2_POS6				1336
#define IDC_EDIT_HapticD_RIGHT_FINGER3_POS1				1337
#define IDC_EDIT_HapticD_RIGHT_FINGER3_POS2				1338
#define IDC_EDIT_HapticD_RIGHT_FINGER3_POS3				1339
#define IDC_EDIT_HapticD_RIGHT_FINGER3_POS4				1340
#define IDC_EDIT_HapticD_RIGHT_FINGER3_POS5				1341
#define IDC_EDIT_HapticD_RIGHT_FINGER3_POS6				1342

#define IDC_EDIT_VIRTUAL_RIGHT_POS1      					1343
#define IDC_EDIT_VIRTUAL_RIGHT_POS2      					1344
#define IDC_EDIT_VIRTUAL_RIGHT_POS3      					1345
#define IDC_EDIT_VIRTUAL_RIGHT_POS4      					1346
#define IDC_EDIT_VIRTUAL_RIGHT_POS5      					1347
#define IDC_EDIT_VIRTUAL_RIGHT_POS6      					1348
#define IDC_EDIT_VIRTUAL_RIGHT_FT1       					1349
#define IDC_EDIT_VIRTUAL_RIGHT_FT2       					1350
#define IDC_EDIT_VIRTUAL_RIGHT_FT3       					1351
#define IDC_EDIT_VIRTUAL_RIGHT_FT4       					1352
#define IDC_EDIT_VIRTUAL_RIGHT_FT5       					1353
#define IDC_EDIT_VIRTUAL_RIGHT_FT6       					1354
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER1_POS1					1355
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER1_POS2					1356
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER1_POS3					1357
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER1_POS4					1358
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER1_POS5					1359
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER1_POS6					1360
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER2_POS1					1361
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER2_POS2					1362
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER2_POS3					1363
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER2_POS4					1364
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER2_POS5					1365
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER2_POS6					1366
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER3_POS1					1367
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER3_POS2					1368
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER3_POS3					1369
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER3_POS4					1370
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER3_POS5					1371
#define IDC_EDIT_VIRTUAL_RIGHT_FINGER3_POS6					1372



#define IDC_EDIT_HapticD_RIGHT_FRIC1                1373
#define IDC_EDIT_HapticD_RIGHT_FRIC2                1374
#define IDC_EDIT_HapticD_RIGHT_FRIC3                1375
#define IDC_EDIT_HapticD_RIGHT_FRIC4                1376
#define IDC_EDIT_HapticD_RIGHT_FRIC5                1377
#define IDC_EDIT_HapticD_RIGHT_FRIC6                1378
#define IDC_EDIT_HapticD_RIGHT_GRAV1                1379
#define IDC_EDIT_HapticD_RIGHT_GRAV2                1380
#define IDC_EDIT_HapticD_RIGHT_GRAV3                1381
#define IDC_EDIT_HapticD_RIGHT_GRAV4                1382
#define IDC_EDIT_HapticD_RIGHT_GRAV5                1383
#define IDC_EDIT_HapticD_RIGHT_GRAV6                1384
#define IDC_EDIT_HapticD_RIGHT_CTRL1               1385
#define IDC_EDIT_HapticD_RIGHT_CTRL2               1386
#define IDC_EDIT_HapticD_RIGHT_CTRL3               1387
#define IDC_EDIT_HapticD_RIGHT_CTRL4               1388
#define IDC_EDIT_HapticD_RIGHT_CTRL5               1389
#define IDC_EDIT_HapticD_RIGHT_CTRL6               1390
#define IDC_EDIT_HapticD_RIGHT_Tq1                  1391
#define IDC_EDIT_HapticD_RIGHT_Tq2                  1392
#define IDC_EDIT_HapticD_RIGHT_Tq3                  1393
#define IDC_EDIT_HapticD_RIGHT_Tq4                  1394
#define IDC_EDIT_HapticD_RIGHT_Tq5                  1395
#define IDC_EDIT_HapticD_RIGHT_Tq6                  1396



#define IDC_CHECK_HapticD_RIGHT_FRIC                 1397
#define IDC_CHECK_HapticD_RIGHT_GRAV                 1398
#define IDC_CHECK_HapticD_RIGHT_CTRL                 1399
#define IDC_EDIT_HapticD_RIGHT_GAIN1         1400
#define IDC_EDIT_HapticD_RIGHT_GAIN2         1401
#define IDC_EDIT_HapticD_RIGHT_GAIN3         1402
#define IDC_EDIT_HapticD_RIGHT_GAIN4         1403
#define IDC_EDIT_HapticD_RIGHT_GAIN5         1404
#define IDC_EDIT_HapticD_RIGHT_GAIN6         1405
#define IDC_EDIT_HapticD_RIGHT_GAIN7         1406
#define IDC_EDIT_HapticD_RIGHT_GAIN8         1407
#define IDC_BUTTON_HapticD_RIGHT_GAIN        1408

#define IDC_RADIO_HapticD_LEFT_CTRL1         1409
#define IDC_RADIO_HapticD_LEFT_CTRL2         1410
#define IDC_RADIO_HapticD_LEFT_CTRL3         1411
#define IDC_RADIO_HapticD_LEFT_CTRL4         1412
#define IDC_RADIO_HapticD_LEFT_CTRL5         1413


#define IDC_RADIO_HapticD_RIGHT_CTRL1        1414
#define IDC_RADIO_HapticD_RIGHT_CTRL2        1415
#define IDC_RADIO_HapticD_RIGHT_CTRL3        1416
#define IDC_RADIO_HapticD_RIGHT_CTRL4        1417
#define IDC_RADIO_HapticD_RIGHT_CTRL5        1418
#define IDC_CHECK_HapticGlove_LEFT_VIRTUAL		1423
#define IDC_CHECK_HapticGlove_RIGHT_VIRTUAL		1424
#define IDC_CHECK_HapticGlove_LEFT_FRIC			1425
#define IDC_CHECK_HapticGlove_RIGHT_FRIC		1426

#define IDC_EDIT_TIP_TAR1	1427
#define IDC_EDIT_TIP_TAR2	1428
#define IDC_EDIT_TIP_TAR3	1429
#define IDC_EDIT_TIP_TAR4	1430
#define IDC_EDIT_TIP_TAR5	1431
#define IDC_EDIT_TIP_TAR6	1432
#define IDC_EDIT_TIP_CUR1	1433
#define IDC_EDIT_TIP_CUR2	1434
#define IDC_EDIT_TIP_CUR3	1435
#define IDC_EDIT_TIP_CUR4	1436
#define IDC_EDIT_TIP_CUR5	1437
#define IDC_EDIT_TIP_CUR6	1438
#define IDC_EDIT_TIP_PWM1	1439
#define IDC_EDIT_TIP_PWM2	1440
#define IDC_EDIT_TIP_PWM3	1441
#define IDC_EDIT_TIP_PWM4	1442
#define IDC_EDIT_TIP_PWM5	1443
#define IDC_EDIT_TIP_PWM6	1444


#define IDC_EDIT_FingerPWM_L_TH1	1445
#define IDC_EDIT_FingerPWM_L_TH2	1446
#define IDC_EDIT_FingerPWM_L_TH3	1447
#define IDC_EDIT_FingerPWM_L_IN1	1448
#define IDC_EDIT_FingerPWM_L_IN2	1449
#define IDC_EDIT_FingerPWM_L_IN3	1450
#define IDC_EDIT_FingerPWM_L_MI1	1451
#define IDC_EDIT_FingerPWM_L_MI2	1452
#define IDC_EDIT_FingerPWM_L_MI3	1453
#define IDC_EDIT_FingerPWM_R_TH1	1454
#define IDC_EDIT_FingerPWM_R_TH2	1455
#define IDC_EDIT_FingerPWM_R_TH3	1456
#define IDC_EDIT_FingerPWM_R_IN1	1457
#define IDC_EDIT_FingerPWM_R_IN2	1458
#define IDC_EDIT_FingerPWM_R_IN3	1459
#define IDC_EDIT_FingerPWM_R_MI1	1460
#define IDC_EDIT_FingerPWM_R_MI2	1461
#define IDC_EDIT_FingerPWM_R_MI3	1462

#define IDC_CHECK_TIP_LEFT_CTRL			1463
#define IDC_CHECK_TIP_RIGHT_CTRL		1464


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
