///////////////////////////////////////////////////////////////////////////////
// ROBOT_HAND_PROJECTClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ROBOT_HAND_PROJECTClassFactory.h"
#include "ROBOT_HAND_PROJECTServices.h"
#include "ROBOT_HAND_PROJECTVersion.h"
#include "Module.h"

BEGIN_CLASS_MAP(CROBOT_HAND_PROJECTClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_ROBOT_HAND_PROJECTCModule, SRVNAME_ROBOT_HAND_PROJECT "!CModule", CModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CROBOT_HAND_PROJECTClassFactory::CROBOT_HAND_PROJECTClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_ROBOT_HAND_PROJECT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(ROBOT_HAND_PROJECT));
#endif //defined(TCDBG_UNIT_VERSION)
}

