///////////////////////////////////////////////////////////////////////////////
// ROBOT_HAND_PROJECTInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "ROBOT_HAND_PROJECTServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
