///////////////////////////////////////////////////////////////////////////////
// ROBOT_HAND_PROJECTServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_ROBOT_HAND_PROJECT = 0x3F000000;
#define SRVNAME_ROBOT_HAND_PROJECT "ROBOT_HAND_PROJECT"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ROBOT_HAND_PROJECTCModule = {0xd57316c5,0x40b5,0x4807,{0x9f,0x1e,0x9f,0x2b,0x86,0xc7,0xc1,0x03}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_ModuleDefaultAdsPort = 0x00000001;
const PTCID PID_ModuleCounter = 0x00000003;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ModuleInputs
{
	SHORT cT1;
	SHORT cT2;
	SHORT cT3;
	SHORT cT4;
	SHORT cT5;
	SHORT cT6;
	SHORT cT7;
	SHORT cT8;
	SHORT cT9;
	SHORT cT10;
} ModuleInputs, *PModuleInputs;

#pragma pack(push,1)
typedef struct _ModuleOutputs
{
	unsigned char cO1;
	unsigned char cO2;
	unsigned char cO3;
} ModuleOutputs, *PModuleOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ModuleInputs 0
#define ADI_ModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
